#define DEBUGWAVEANALYSIS

#define MAXLENGTH 32768

// CFD Parameters
#define CFDPARPRITRIGGER    500
#define CFDPARSMOOTHLENGTH  60
#define CFDPARRISELENGTH    60
#define CFDPARTHRESHOLD     30

// Trapezoid Parameters
#define TRAPPARDECAYLENGTH  1800
#define TRAPPARRISELENGTH   500
#define TRAPPARFLATTOP      100
#define TRAPPARPRITRIGGER   500
#define TRAPPARPEAKDELAY    500
#define TRAPPARPEAKMEAN     1
