//#define DEBUGWAVEANALYSIS
//#define DEBUGDRAWOPTION

#define MAXLENGTH 32768
#define POLARITY 1

// CFD Parameters
#define CFDPARPRITRIGGER    500
#define CFDPARSMOOTHLENGTH  60
#define CFDPARRISELENGTH    60
#define CFDPARTHRESHOLD     30

// Trapezoid Parameters
#define TRAPPARDECAYLENGTH  1800
#define TRAPPARRISELENGTH   500
#define TRAPPARFLATTOP      100
#define TRAPPARPRITRIGGER   500
#define TRAPPARPEAKDELAY    0
#define TRAPPARPEAKMEAN     0

//
#define PILEUPMAX 2

// PID
#define Q1START  1000
#define Q1STOP   1200
#define Q2START  1200
#define Q2STOP   3000
